import { jsPDF } from 'jspdf';
import { AssessmentResult, ClubBrandConfig } from '../types';
import { Language } from '../data/translations';

export function generatePdfReport(
  result: AssessmentResult, 
  lang: Language = 'es',
  clubBrand?: ClubBrandConfig | null
) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Color Palette Constants
  const darkBg = [10, 15, 29]; // #0a0f1d
  const cardBg = [19, 27, 46]; // #131b2e
  const voltColor = [204, 255, 0]; // #ccff00
  const cyanColor = [78, 146, 242]; // #4e92f2
  const textColor = [255, 255, 255];
  const mutedText = [148, 163, 184]; // slate-400

  // 1. Page Background
  doc.setFillColor(darkBg[0], darkBg[1], darkBg[2]);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  // Top Accent Neon Bar
  doc.setFillColor(voltColor[0], voltColor[1], voltColor[2]);
  doc.rect(0, 0, pageWidth, 4, 'F');

  // Translations dictionary for the PDF
  const t = {
    en: {
      brand: 'COACHSTRIKE AI',
      subtitle: 'UEFA PRO TACTICAL DNA SCOUTING REPORT',
      ref: 'REF ID:',
      date: 'DATE:',
      playerLabel: 'PLAYER PROFILE',
      footLabel: 'PREFERRED FOOT:',
      positionLabel: 'PRIMARY IDEAL POSITION',
      matchScore: 'COMPATIBILITY MATCH',
      skillsTitle: 'TACTICAL DNA ATTRIBUTES (0-99 SCALE)',
      proMatchTitle: 'PRO PLAYER BENCHMARK & COMPARISON',
      affinity: 'AFFINITY',
      tacticalDuties: 'ON-FIELD TACTICAL RESPONSIBILITIES',
      strengths: 'KEY STRENGTHS',
      areasToImprove: 'AREAS FOR DEVELOPMENT',
      drillsTitle: 'PRIORITY TRAINING FOCUS',
      footerCert: 'Official Tactical Analysis generated by CoachStrike AI Scouting Engine.',
      confidential: 'CONFIDENTIAL • ATHLETE PERFORMANCE DOSSIER',
      pac: 'Speed / Pace',
      tec: 'Technique & First Touch',
      fin: 'Finishing & Shot',
      pas: 'Passing & Vision',
      def: 'Defending & Anticipation',
      phy: 'Physical & Stamina',
      tac: 'Tactical IQ & Awareness',
      men: 'Mental & Composure'
    },
    es: {
      brand: 'COACHSTRIKE AI',
      subtitle: 'INFORME SCOUTING DE ADN TÁCTICO UEFA PRO',
      ref: 'REF ID:',
      date: 'FECHA:',
      playerLabel: 'PERFIL DEL JUGADOR',
      footLabel: 'PIE DOMINANTE:',
      positionLabel: 'POSICIÓN IDEAL PRINCIPAL',
      matchScore: 'COMPATIBILIDAD',
      skillsTitle: 'ATRIBUTOS ADN TÁCTICO (ESCALA 0-99)',
      proMatchTitle: 'COMPARATIVA CON JUGADOR PROFESIONAL',
      affinity: 'AFINIDAD',
      tacticalDuties: 'OBLIGACIONES TÁCTICAS EN EL CAMPO',
      strengths: 'PUNTOS FUERTES',
      areasToImprove: 'ÁREAS DE MEJORA PRIORITARIAS',
      drillsTitle: 'ENFOQUES DE ENTRENAMIENTO RECOMENDADOS',
      footerCert: 'Informe oficial de análisis táctico generado por el motor CoachStrike AI.',
      confidential: 'CONFIDENCIAL • DOSSIER DE RENDIMIENTO DEPORTIVO',
      pac: 'Velocidad y Aceleración',
      tec: 'Técnica y Control',
      fin: 'Definición y Golpeo',
      pas: 'Pase y Visión de Juego',
      def: 'Defensa y Anticipación',
      phy: 'Físico y Resistencia',
      tac: 'Inteligencia Táctica',
      men: 'Fuerza Mental y Temple'
    },
    pt: {
      brand: 'COACHSTRIKE AI',
      subtitle: 'RELATÓRIO DE SCOUTING TÁTICO UEFA PRO',
      ref: 'REF ID:',
      date: 'DATA:',
      playerLabel: 'PERFIL DO JOGADOR',
      footLabel: 'PÉ DOMINANTE:',
      positionLabel: 'POSIÇÃO IDEAL PRINCIPAL',
      matchScore: 'COMPATIBILIDADE',
      skillsTitle: 'ATRIBUTOS DE ADN TÁTICO (ESCALA 0-99)',
      proMatchTitle: 'COMPARATIVO COM JOGADOR PROFISSIONAL',
      affinity: 'AFINIDADE',
      tacticalDuties: 'OBRIGAÇÕES TÁTICAS NO TERRENO DE JOGO',
      strengths: 'PONTOS FORTES',
      areasToImprove: 'ÁREAS DE DESENVOLVIMENTO',
      drillsTitle: 'FOCOS DE TREINO RECOMENDADOS',
      footerCert: 'Relatório oficial de análise tática gerado pelo motor CoachStrike AI.',
      confidential: 'CONFIDENCIAL • DOSSIER DE DESEMPENHO ATLETA',
      pac: 'Velocidade e Aceleração',
      tec: 'Técnica e Primeiro Toque',
      fin: 'Finalização e Remate',
      pas: 'Passe e Visão de Jogo',
      def: 'Defesa e Antecipação',
      phy: 'Físico e Resistência',
      tac: 'Inteligência Tática',
      men: 'Capacidade Mental e Foco'
    }
  }[lang] || {
    brand: 'COACHSTRIKE AI',
    subtitle: 'UEFA PRO TACTICAL DNA SCOUTING REPORT',
    ref: 'REF ID:',
    date: 'DATE:',
    playerLabel: 'PLAYER PROFILE',
    footLabel: 'PREFERRED FOOT:',
    positionLabel: 'PRIMARY IDEAL POSITION',
    matchScore: 'COMPATIBILITY MATCH',
    skillsTitle: 'TACTICAL DNA ATTRIBUTES (0-99 SCALE)',
    proMatchTitle: 'PRO PLAYER BENCHMARK & COMPARISON',
    affinity: 'AFFINITY',
    tacticalDuties: 'ON-FIELD TACTICAL RESPONSIBILITIES',
    strengths: 'KEY STRENGTHS',
    areasToImprove: 'AREAS FOR DEVELOPMENT',
    drillsTitle: 'PRIORITY TRAINING FOCUS',
    footerCert: 'Official Tactical Analysis generated by CoachStrike AI Scouting Engine.',
    confidential: 'CONFIDENTIAL • ATHLETE PERFORMANCE DOSSIER',
    pac: 'Speed / Pace',
    tec: 'Technique & First Touch',
    fin: 'Finishing & Shot',
    pas: 'Passing & Vision',
    def: 'Defending & Anticipation',
    phy: 'Physical & Stamina',
    tac: 'Tactical IQ & Awareness',
    men: 'Mental & Composure'
  };

  let cursorY = 16;

  // Load saved club brand from localStorage if not explicitly provided
  let activeBrand = clubBrand;
  if (!activeBrand && typeof window !== 'undefined') {
    try {
      const stored = localStorage.getItem('coachstrike_club_brand');
      if (stored) activeBrand = JSON.parse(stored);
    } catch {}
  }

  // Header Section
  doc.setFont('helvetica', 'bold');
  if (activeBrand && activeBrand.clubName) {
    doc.setFontSize(15);
    doc.setTextColor(voltColor[0], voltColor[1], voltColor[2]);
    doc.text(activeBrand.clubName.toUpperCase(), 15, cursorY);

    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(mutedText[0], mutedText[1], mutedText[2]);
    const subtitleText = activeBrand.clubMotto 
      ? `${activeBrand.clubMotto.toUpperCase()} • ${t.subtitle}`
      : `${activeBrand.clubName} • ${t.subtitle}`;
    doc.text(subtitleText, 15, cursorY + 5);
  } else {
    doc.setFontSize(18);
    doc.setTextColor(voltColor[0], voltColor[1], voltColor[2]);
    doc.text(t.brand, 15, cursorY);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(mutedText[0], mutedText[1], mutedText[2]);
    doc.text(t.subtitle, 15, cursorY + 5);
  }

  doc.setFontSize(8);
  doc.setFont('courier', 'bold');
  doc.setTextColor(mutedText[0], mutedText[1], mutedText[2]);
  const dateStr = result.createdAt || new Date().toLocaleDateString();
  doc.text(`${t.ref} #STK-${result.id.slice(-6).toUpperCase()}`, pageWidth - 15, cursorY, { align: 'right' });
  doc.text(`${t.date} ${dateStr}`, pageWidth - 15, cursorY + 5, { align: 'right' });

  cursorY += 12;

  // Horizontal Divider
  doc.setDrawColor(255, 255, 255, 0.1);
  doc.setLineWidth(0.3);
  doc.line(15, cursorY, pageWidth - 15, cursorY);
  cursorY += 6;

  // Player Name & Primary Position Hero Card
  doc.setFillColor(cardBg[0], cardBg[1], cardBg[2]);
  doc.roundedRect(15, cursorY, pageWidth - 30, 28, 3, 3, 'F');

  // Left Player Info
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(mutedText[0], mutedText[1], mutedText[2]);
  doc.text(t.playerLabel, 20, cursorY + 7);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  doc.text(result.playerName.toUpperCase(), 20, cursorY + 15);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(voltColor[0], voltColor[1], voltColor[2]);
  doc.text(`${t.footLabel} ${result.preferredFoot.toUpperCase()}`, 20, cursorY + 22);

  // Right Primary Position
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(mutedText[0], mutedText[1], mutedText[2]);
  doc.text(t.positionLabel, pageWidth - 20, cursorY + 7, { align: 'right' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(voltColor[0], voltColor[1], voltColor[2]);
  doc.text(result.primaryPosition.title.toUpperCase(), pageWidth - 20, cursorY + 15, { align: 'right' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(cyanColor[0], cyanColor[1], cyanColor[2]);
  doc.text(`${result.primaryPosition.matchPercentage}% ${t.matchScore}`, pageWidth - 20, cursorY + 22, { align: 'right' });

  cursorY += 34;

  // 8D Tactical Attributes Grid
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(voltColor[0], voltColor[1], voltColor[2]);
  doc.text(t.skillsTitle, 15, cursorY);
  cursorY += 4;

  const skillsList = [
    { label: t.pac, val: result.skills.speed, code: 'PAC' },
    { label: t.tec, val: result.skills.technique, code: 'TEC' },
    { label: t.fin, val: result.skills.finishing, code: 'SHO' },
    { label: t.pas, val: result.skills.passing, code: 'PAS' },
    { label: t.def, val: result.skills.defending, code: 'DEF' },
    { label: t.phy, val: result.skills.physical, code: 'PHY' },
    { label: t.tac, val: result.skills.tacticalIQ, code: 'TAC' },
    { label: t.men, val: result.skills.mental, code: 'MEN' }
  ];

  const colWidth = (pageWidth - 30 - 6) / 2;
  const barHeight = 8.5;

  skillsList.forEach((skill, idx) => {
    const isLeft = idx % 2 === 0;
    const row = Math.floor(idx / 2);
    const x = isLeft ? 15 : 15 + colWidth + 6;
    const y = cursorY + row * (barHeight + 2.5);

    // Box Container
    doc.setFillColor(cardBg[0], cardBg[1], cardBg[2]);
    doc.roundedRect(x, y, colWidth, barHeight, 2, 2, 'F');

    // Text Label
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(textColor[0], textColor[1], textColor[2]);
    doc.text(skill.label, x + 3, y + 5.5);

    // Score Number
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(voltColor[0], voltColor[1], voltColor[2]);
    doc.text(`${skill.val}/100`, x + colWidth - 3, y + 5.5, { align: 'right' });

    // Progress Bar Background
    const barW = colWidth - 6;
    const barFilledW = (barW * skill.val) / 100;
    doc.setFillColor(255, 255, 255, 0.08);
    doc.rect(x + 3, y + 7, barW, 0.8, 'F');

    // Progress Bar Filled
    doc.setFillColor(voltColor[0], voltColor[1], voltColor[2]);
    doc.rect(x + 3, y + 7, barFilledW, 0.8, 'F');
  });

  cursorY += 4 * (barHeight + 2.5) + 6;

  // Pro Player Benchmark Box
  doc.setFillColor(cardBg[0], cardBg[1], cardBg[2]);
  doc.roundedRect(15, cursorY, pageWidth - 30, 24, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(voltColor[0], voltColor[1], voltColor[2]);
  doc.text(t.proMatchTitle, 20, cursorY + 6);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  doc.text(`${result.proComparison.player.name.toUpperCase()} (${result.proComparison.player.club})`, 20, cursorY + 12);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(cyanColor[0], cyanColor[1], cyanColor[2]);
  doc.text(`${result.proComparison.matchPercentage}% ${t.affinity}`, pageWidth - 20, cursorY + 12, { align: 'right' });

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7);
  doc.setTextColor(mutedText[0], mutedText[1], mutedText[2]);
  const splitReason = doc.splitTextToSize(result.proComparison.matchReason, pageWidth - 40);
  doc.text(splitReason.slice(0, 2), 20, cursorY + 17);

  cursorY += 30;

  // Tactical Responsibilities Card
  doc.setFillColor(cardBg[0], cardBg[1], cardBg[2]);
  doc.roundedRect(15, cursorY, pageWidth - 30, 26, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(voltColor[0], voltColor[1], voltColor[2]);
  doc.text(t.tacticalDuties, 20, cursorY + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  const duties = (result.primaryPosition as any).tacticalDuties || 
    (result.tacticalZones && result.tacticalZones.length > 0 ? result.tacticalZones.map(z => z.roleDescription) : [result.primaryPosition.roleDescription]);
  duties.slice(0, 3).forEach((duty: string, dIdx: number) => {
    const textSnippet = duty.length > 85 ? `${duty.slice(0, 85)}...` : duty;
    doc.text(`• ${textSnippet}`, 20, cursorY + 12 + dIdx * 4.5);
  });

  cursorY += 32;

  // Two columns: Key Strengths & Areas for Improvement
  const halfColW = (pageWidth - 30 - 6) / 2;

  // Left: Key Strengths
  doc.setFillColor(cardBg[0], cardBg[1], cardBg[2]);
  doc.roundedRect(15, cursorY, halfColW, 28, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(cyanColor[0], cyanColor[1], cyanColor[2]);
  doc.text(`✓ ${t.strengths}`, 20, cursorY + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  (result.strengths || []).slice(0, 3).forEach((str, sIdx) => {
    const textSnippet = str.length > 42 ? `${str.slice(0, 42)}...` : str;
    doc.text(`• ${textSnippet}`, 20, cursorY + 12 + sIdx * 5);
  });

  // Right: Areas to Improve
  doc.setFillColor(cardBg[0], cardBg[1], cardBg[2]);
  doc.roundedRect(15 + halfColW + 6, cursorY, halfColW, 28, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(voltColor[0], voltColor[1], voltColor[2]);
  doc.text(`▲ ${t.areasToImprove}`, 20 + halfColW + 6, cursorY + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  (result.areasToImprove || []).slice(0, 3).forEach((area, aIdx) => {
    const textSnippet = area.length > 42 ? `${area.slice(0, 42)}...` : area;
    doc.text(`• ${textSnippet}`, 20 + halfColW + 6, cursorY + 12 + aIdx * 5);
  });

  cursorY += 34;

  // Priority Training Focus
  doc.setFillColor(cardBg[0], cardBg[1], cardBg[2]);
  doc.roundedRect(15, cursorY, pageWidth - 30, 24, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(voltColor[0], voltColor[1], voltColor[2]);
  doc.text(`⚡ ${t.drillsTitle}`, 20, cursorY + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  (result.recommendedDrills || []).slice(0, 2).forEach((drill, drIdx) => {
    const detail = `${drill.title} (${drill.category} - ${drill.difficulty})`;
    const textSnippet = detail.length > 80 ? `${detail.slice(0, 80)}...` : detail;
    doc.text(`• ${textSnippet}`, 20, cursorY + 12 + drIdx * 5);
  });

  // Footer Certificate Note
  if (activeBrand?.directorName) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(6.5);
    doc.setTextColor(textColor[0], textColor[1], textColor[2]);
    const roleTitle = activeBrand.directorTitle ? activeBrand.directorTitle.toUpperCase() : 'DIRECTOR DEPORTIVO / CANTERA';
    doc.text(`VALIDADO POR: ${activeBrand.directorName.toUpperCase()} — ${roleTitle}`, pageWidth / 2, pageHeight - 12, { align: 'center' });
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(6.5);
  doc.setTextColor(mutedText[0], mutedText[1], mutedText[2]);
  doc.text(t.footerCert, pageWidth / 2, pageHeight - 8, { align: 'center' });

  doc.setFontSize(6);
  doc.setTextColor(mutedText[0], mutedText[1], mutedText[2]);
  doc.text(t.confidential, pageWidth / 2, pageHeight - 4.5, { align: 'center' });

  // Save the PDF
  const sanitizedName = result.playerName.replace(/[^a-zA-Z0-9_-]/g, '_');
  doc.save(`CoachStrike_Report_${sanitizedName}.pdf`);
}
